name: CI 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Rust CI
  rust-ci:
    name: Rust CI
    uses: ./.github/workflows/ci-rust.yml

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [rust-ci]
    if: always()
    steps:
      - name: Check if all jobs succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more jobs failed"
            exit 1
          fi
          echo "All CI checks passed! ✅"
