name: Publish to crates.io

on:
  push:
    tags:
      - "jax-common-v*"
      - "jax-service-v*"
      - "jax-bucket-v*"
    branches:
      - main
    paths:
      - ".github/workflows/publish-crate.yml"

jobs:
  publish:
    name: Publish jax-bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: rust/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-

      - name: Run tests
        run: cargo test --all

      - name: Publish crates to crates.io (in order with delays)
        run: |
          # Publish in dependency order with delays for crates.io indexing

          # Check if jax-common tag exists and needs publishing
          if git tag -l | grep -q "jax-common-v"; then
            COMMON_VERSION=$(git describe --tags --match "jax-common-v*" --abbrev=0 2>/dev/null | sed 's/jax-common-v//')
            if [ -n "$COMMON_VERSION" ]; then
              echo "Publishing jax-common v$COMMON_VERSION..."
              cd crates/common
              cargo publish --token $CARGO_REGISTRY_TOKEN || echo "jax-common already published or failed"
              cd ../..
              echo "Waiting 30s for crates.io to index..."
              sleep 30
            fi
          fi

          # Check if jax-service tag exists and needs publishing
          if git tag -l | grep -q "jax-service-v"; then
            SERVICE_VERSION=$(git describe --tags --match "jax-service-v*" --abbrev=0 2>/dev/null | sed 's/jax-service-v//')
            if [ -n "$SERVICE_VERSION" ]; then
              echo "Publishing jax-service v$SERVICE_VERSION..."
              cd crates/service
              cargo publish --token $CARGO_REGISTRY_TOKEN || echo "jax-service already published or failed"
              cd ../..
              echo "Waiting 30s for crates.io to index..."
              sleep 30
            fi
          fi

          # Check if jax-bucket tag exists and needs publishing
          if git tag -l | grep -q "jax-bucket-v"; then
            BUCKET_VERSION=$(git describe --tags --match "jax-bucket-v*" --abbrev=0 2>/dev/null | sed 's/jax-bucket-v//')
            if [ -n "$BUCKET_VERSION" ]; then
              echo "Publishing jax-bucket v$BUCKET_VERSION..."
              cd crates/app
              cargo publish --token $CARGO_REGISTRY_TOKEN || echo "jax-bucket already published or failed"
              cd ../..
            fi
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
